apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: macedonia-regions
data:
  NODE_ENV: "production"
  NEXTAUTH_URL: "http://164.92.240.237"
  AUTH_TRUST_HOST: "true"
  R2_ENDPOINT: "https://a223e53d31cc34c5968ee9c0a674903a.r2.cloudflarestorage.com"
  R2_BUCKET_NAME: "macedonia-regions"
  R2_PUBLIC_URL: "https://pub-b9d54b7cd30042a0aab7e0c72155183d.r2.dev"
