apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: macedonia-regions
type: Opaque
stringData:
  database-url: "postgresql://neondb_owner:npg_fEQx79NLzopm@ep-delicate-fog-agkxpuhp-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
  nextauth-secret: "k7Xp2mN9qR4sT8vB3wY6zA1cD5eF0gH2jK7mP9rS4tU="
  auth-secret: "k7Xp2mN9qR4sT8vB3wY6zA1cD5eF0gH2jK7mP9rS4tU="
  r2-access-key-id: "63bb03608e39a2c087caa9c4331e9d0c"
  r2-secret-access-key: "a97c7bea81e2c7b5e6eb59596e49d354cff215648568a2b74b05dccdb503363b"
